function value = linear_spike_inverse_cdf(percentile,center,spread)
    value = (percentile == 0) .* (center- spread) + ...
        (percentile > 0 & percentile <= 1/2) .* (center - spread + sqrt(2).*spread.*sqrt(percentile)) + ...
        (percentile > 1/2 & percentile < 1) .* (center + spread - sqrt(2).*spread.*sqrt(1-percentile)) + ...
        (percentile == 1) .* (center + spread);
end