function value = linear_spike_cdf(p,center,spread)
    value = ((p >= (center - spread)) & (p <= center)) .* 1/2/spread^2.*(p-center+spread).^2 + ...
        ((p > center) & (p < (center + spread))) .* (1-1/2/(spread^2)*(center+spread-p).^2) + ...
        (p >= (center + spread)) .* 1;
end